---
title: "MSD 2019 Final Project"
subtitle: "An extension (regularized model) of Greed and Grievance in Civil War by Paul Collier and Anke Hoeffler, 2000"
author: "Kiran Ramesh (kr2789), Sai Srujan Chinta (sc4401), Bhavya Shahi (bs3118)"
date: '`r Sys.time()`'
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
params:
  threshold: "0.5"
---

```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)
library(foreign)
library(DescTools)
library(lme4)
library(ROCR)
library(glmnet)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE, warning = FALSE)
```

# Reading Data

```{r read-data}

setwd(".")
options("scipen"=100, "digits"=4)

data <- read.dta("data/G&G.dta")
data <- data[!is.na(data$warsa),]

```

#Helper Functions
```{r helper-functions}
summarize_into_table <- function(summary_obj)
{
  #takes summary object as input, and returns a DF res. 
  #to print res, use print(summ(obj), quote = FALSE) is you don't want quotes
  
  options(digits = 4)
  res <- t(round(summary_obj$coefficients, digits = 4))
  z.values <- res[4,]
  Signif <- symnum(z.values, corr = FALSE, na = FALSE, cutpoints = c(0, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ""))
  res <- rbind(res, Signif)
  res <- t(res)
  res <- res[-1,]
  res
}

comma_sep = function(x) {
    x = strsplit(x, "")
}

convert2dArrayToDf = function(all_tests) {
  model_names <- all_tests[,1]

  invisible(apply(all_tests, 2, as.numeric))
  invisible(sapply(all_tests, as.numeric))
  class(all_tests) <- "numeric"
  storage.mode(all_tests) <- "numeric"
  
  all_tests <- as.data.frame(all_tests)
  
  all_tests[,1] <- model_names
  
  return(all_tests)
}
```

#Free variables

```{r reading-data}

k <- 5

all_tests <- matrix(data=0, nrow=k, ncol=6)
colnames(all_tests) <- c("model", "test_index", "sens", "spec", "auc", "accuracy")

set.seed(42)
shuffled_data <- data[sample(nrow(data)),]
folds <- cut(seq(1, nrow(shuffled_data)), breaks=k, labels=FALSE)

thresholding_flag = TRUE

threshold_value = as.numeric(params$threshold)

sens_index <- 3
spec_index <- 4
auc_index <- 5
accuracy_index <- 6

```

# Regularized Model

```{r regularized-model}

for(testIndex in 1:k){
  
  regularized.data <- shuffled_data %>% select(warsa, coldwar, prevwara, peace, elfo, rf, frac, geogia, mount, lnpop, sxp, sxp2, dem, ygini, lgini, lngdp_, gy1, secm, diaspeaa, difdpeaa, diahpeaa, pol16, oilsxp, oilsxp2, etdo4590)
  
  #Segement your data by fold using the which() function 
  testIndexes <- which(folds == testIndex,arr.ind=TRUE)
  testData <- regularized.data[testIndexes, ]
  trainData <- regularized.data[-testIndexes, ]
  
  trainData <- na.omit(trainData)
  testData <- na.omit(testData)
  
  train_x <- as.matrix(trainData[, 2:ncol(trainData)])
  train_y <- as.matrix(trainData$warsa)
  
  test_x <- as.matrix(testData[, 2:ncol(testData)])
  test_y <- as.matrix(testData$warsa)

  regularized_fit <- cv.glmnet(x=train_x, y=train_y, family="binomial", type.measure="auc")
  regularized_predict <- predict(regularized_fit, test_x, type="response", s="lambda.min")
  
  regularized_y.hat <- as.matrix(regularized_predict)

  all_tests[testIndex,1] <- paste(c("regularized"), collapse = '.')
  all_tests[testIndex,2] <- as.numeric(testIndex)
  
  regularized_y.hat_normalized <- regularized_y.hat
    
  regularized_y.hat_normalized[regularized_y.hat_normalized >= threshold_value] <- 1
  regularized_y.hat_normalized[regularized_y.hat_normalized < threshold_value] <- 0
  
  regularized_predict_normalized <- prediction(regularized_y.hat_normalized, test_y)

  len <- length(regularized_predict_normalized@fp[[1]])
  fp <- as.numeric(regularized_predict_normalized@fp[[1]][[len - 1]])
  tp <- as.numeric(regularized_predict_normalized@tp[[1]][[len - 1]])
  fn <- as.numeric(regularized_predict_normalized@fn[[1]][[len - 1]])
  tn <- as.numeric(regularized_predict_normalized@tn[[1]][[len - 1]])
  
  all_tests[testIndex,sens_index] <- tp / (tp + fn)
  all_tests[testIndex,spec_index] <- tn / (tn + fp)
  
  all_tests[testIndex,accuracy_index] <- (tp + tn) / (tp + tn + fp + fn)
  
  regularized_predict <- prediction(regularized_y.hat, test_y)
  regular_auc <- performance(regularized_predict, measure = "auc")
  all_tests[testIndex,auc_index] <- as.numeric(unlist(slot(regular_auc,"y.values")))
}

lower_lim = 1
upper_lim = k
print(convert2dArrayToDf(all_tests[lower_lim:upper_lim,1:6]))
```

# Converting Results into DataFrame

```{r final-result}
all_tests <- convert2dArrayToDf(all_tests)

result <- aggregate(all_tests[, 3:6], list(all_tests$model), mean)

names(result)[1]<-"model"

print(result)

write.csv(result, file = paste0("Project_Extension_3_Threshold_", params$threshold, ".csv"))
```

The following is a list of all packages used to generate these results. (Leave at very end of file.)

```{r}
sessionInfo()
```